repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.269'
    hooks:
      - id: ruff
        args: [ --fix, --exit-non-zero-on-fix ]

  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
        language_version: python3.10

  - repo: https://github.com/djlint/djLint
    rev: v1.34.1
    hooks:
      - id: djlint-reformat-django

  - repo: https://github.com/biomejs/pre-commit
    rev: ""  # Use the sha / tag you want to point at
    hooks:
      - id: biome-format
        additional_dependencies: ["@biomejs/biome@1.4.1"]
        exclude: '^.+\.min\.js$'