# Generated by Django 5.0.2 on 2024-04-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Part",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=30)),
                ("part_xml", models.TextField()),
                ("plan_image", models.ImageField(upload_to="plans")),
            ],
        ),
    ]
