# Generated by Django 5.0.2 on 2024-04-15 06:29

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Part",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=30)),
                ("xml_fn", models.CharField(max_length=100)),
                ("plan_fn", models.CharField(max_length=100)),
            ],
        ),
    ]
