# Generated by Django 5.0.2 on 2024-04-20 08:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="part",
            name="plan_image",
            field=models.ImageField(blank=True, null=True, upload_to="plans"),
        ),
    ]
