# Generated by Django 5.0.2 on 2024-04-20 13:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_alter_part_plan_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                ("id", models.CharField(max_length=200, primary_key=True, serialize=False)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("mathematical", "Mathematical"),
                            ("physical", "Physical"),
                            ("informatical", "Informatical"),
                            ("didactic", "Didactic"),
                            ("support", "Support"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                ("id", models.CharField(max_length=100, primary_key=True, serialize=False)),
                ("text", models.CharField(max_length=100)),
                ("icon", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Purpose",
            fields=[
                ("id", models.CharField(max_length=100, primary_key=True, serialize=False)),
                ("text", models.CharField(max_length=100)),
                ("icon", models.CharField(blank=True, max_length=100, null=True)),
                ("colour", models.CharField(blank=True, max_length=20, null=True)),
                ("interesting", models.BooleanField(default=False)),
                ("free_room_candidate", models.BooleanField(default=False)),
                ("default", models.BooleanField(default=False)),
            ],
        ),
    ]
