# Generated by Django 5.0.2 on 2024-04-22 14:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_department_item_purpose"),
    ]

    operations = [
        migrations.AddField(
            model_name="part",
            name="plan_x_offset",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="part",
            name="plan_y_offset",
            field=models.IntegerField(default=0),
        ),
    ]
