# Generated by Django 5.0.2 on 2024-04-26 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_part_plan_x_offset_part_plan_y_offset"),
    ]

    operations = [
        migrations.RenameField(
            model_name="part",
            old_name="plan_x_offset",
            new_name="dx",
        ),
        migrations.RenameField(
            model_name="part",
            old_name="plan_y_offset",
            new_name="dy",
        ),
        migrations.AddField(
            model_name="part",
            name="level",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="part",
            name="pavilion",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="part",
            name="scale_x",
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name="part",
            name="scale_y",
            field=models.FloatField(default=1),
        ),
    ]
