# Generated by Django 5.0.2 on 2024-04-29 13:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_pavilion"),
    ]

    operations = [
        migrations.RenameField(
            model_name="part",
            old_name="dx",
            new_name="plan_x_offset",
        ),
        migrations.RenameField(
            model_name="part",
            old_name="dy",
            new_name="plan_y_offset",
        ),
    ]
