# Generated by Django 5.0.2 on 2024-04-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_rename_dx_part_plan_x_offset_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="part",
            name="dx",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="part",
            name="dy",
            field=models.IntegerField(default=0),
        ),
    ]
