# Generated by Django 5.0.2 on 2024-04-29 14:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0008_part_dx_part_dy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="part",
            name="name",
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
