# Generated by Django 5.0.2 on 2024-05-13 10:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0009_alter_part_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="part",
            name="pavilion",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
